name: kasie_transie_marshal
description: Marshal Version 3.0
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  kasie_transie_library:
    path: ../kasie_transie_library
  cupertino_icons: ^1.0.5
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.5.0
  focused_menu: ^1.0.5
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
    - assets/markers/
    - assets/numbers/
    - .env
