name: kasie_transie_marshal
description: Marshal Version 3.0
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  kasie_transie_library:
    path: ../kasie_transie_library
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^14.1.1
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.3.1
  page_transition: ^2.0.9
  responsive_builder: ^0.7.0
  flutter_riverpod: ^2.3.6
  pretty_json: ^2.0.0
  geolocator: ^9.0.2
  focused_menu: ^1.0.5
  firebase_ui_auth: ^1.4.3
  intl: ^0.18.0
  flutter_polyline_points:
  dots_indicator:
  realm:
  uuid:
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
    - assets/markers/
    - assets/numbers/
